### ISSUE TITLE
Importing Posts to Parse

### ISSUE THREAD

**Issue by aalzanki** [MakeSchool-Tutorials/Makestagram-Swift-Part2#2]
Importing the posts to Parse (https://github.com/MakeSchool-Tutorials/Makestagram-Swift-Part2/blob/master/P20-Friend-Search/content.md) doesn't include the images. Trying to access the image on Parse returns the following error:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>204F4409E63F34B9</RequestId>
<HostId>
pcSrP9V7k3UtLfcobvwz4ZNce3Pdlc9agD+/+286MzFQosx5d4O5r1g6hcLxcRnVGukS5LJTp+s=
</HostId>
</Error>

**Comment by Ben-G** [comment]
Thanks for pointing out! Unfortunately there's probably no easy fix for now.
