### ISSUE TITLE
Missing Image

### ISSUE THREAD

**Issue by aalzanki** [MakeSchool-Tutorials/Makestagram-Swift-Part2#4]
The image after the first paragraph is missing:
https://github.com/MakeSchool-Tutorials/Makestagram-Swift-Part2/blob/master/P24-Post-Headers/content.md

**Comment by ghost** [comment]
I think this was due to the image markdown being malformed; fixed in 8577588?

**Comment by aalzanki** [comment]
Yeah great, it works!
